// Bilingual content for the service landing pages (services/<slug>.html and services/<slug>-ar.html).
// Every text entry is { en, ar }. Built by build-services.js.

const HUB = 'mep-contracting';

const SERVICES = [
  {
    slug: HUB,
    hub: true,
    icon: 'gear',
    img: { base: 'img/hero', widths: [800, 1400, 2000] },
    imgAlt: { en: 'Glass-façade office tower', ar: 'برج مكتبي بواجهة زجاجية' },
    name: { en: 'MEP Contracting Services', ar: 'خدمات المقاولات الكهروميكانيكية' },
    short: { en: 'All MEP services', ar: 'جميع الخدمات' },
    seoTitle: { en: 'MEP Contracting Services in Saudi Arabia | Barakat Arabia', ar: 'مقاولات الأعمال الكهروميكانيكية في السعودية | البركات العربية' },
    desc: {
      en: 'MEP contractor in Saudi Arabia: HVAC, firefighting, electrical, plumbing, BMS, low current, solar, power backup and facility management from one team.',
      ar: 'مقاول أعمال كهروميكانيكية في السعودية: تكييف، مكافحة حريق، كهرباء، أعمال صحية، BMS، تيار خفيف، طاقة شمسية، طاقة احتياطية وإدارة مرافق.',
    },
    h1: { en: 'MEP contracting, from <em>design to maintenance</em>', ar: 'مقاولات كهروميكانيكية <em>من التصميم إلى الصيانة</em>' },
    lead: {
      en: 'One accountable team for the mechanical, electrical and plumbing systems that make buildings work — across Saudi Arabia and the region.',
      ar: 'فريق واحد مسؤول عن الأنظمة الميكانيكية والكهربائية والصحية التي تُشغّل المباني — في المملكة العربية السعودية والمنطقة.',
    },
    chips: [{ en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' }, { en: '20+ years', ar: '+20 عاماً' }, { en: '500+ projects', ar: '+500 مشروع' }],
    overview: [
      {
        en: 'Barakat Arabia is a general contracting and MEP company that supplies, installs and maintains electromechanical systems for commercial, healthcare, hospitality, industrial, residential and infrastructure projects.',
        ar: 'البركات العربية شركة مقاولات عامة وأعمال كهروميكانيكية، تورّد الأنظمة الكهروميكانيكية وتركّبها وتصونها لمشاريع تجارية وصحية وفندقية وصناعية وسكنية ومشاريع البنية التحتية.',
      },
      {
        en: 'Our engineers take a project from value review, engineering calculations and shop drawings through procurement, installation, testing and commissioning — and stay on after handover with operation and maintenance. With more than 20 years of experience and over 500 completed projects, including the Misk City Mobility Hub and the Dental Center at King Saud Medical City in Riyadh, clients get a single contractor coordinating every system on site.',
        ar: 'يتولى مهندسونا المشروع بدءاً من مراجعة القيمة والحسابات الهندسية والمخططات التنفيذية، مروراً بالتوريد والتركيب والاختبار والتشغيل التجريبي، ونبقى مع العميل بعد التسليم عبر خدمات التشغيل والصيانة. وبخبرة تتجاوز 20 عاماً وأكثر من 500 مشروع منجز، منها مركز التنقل بمدينة مسك ومركز طب الأسنان بمدينة الملك سعود الطبية في الرياض، يحصل العميل على مقاول واحد ينسّق جميع الأنظمة في الموقع.',
      },
    ],
    scopeTitle: { en: 'Systems we deliver', ar: 'الأنظمة التي ننفذها' },
    scope: [
      { en: 'HVAC & ventilation', ar: 'التكييف والتهوية' },
      { en: 'Firefighting & fire alarm', ar: 'مكافحة الحريق وإنذار الحريق' },
      { en: 'Electrical power & lighting', ar: 'القوى الكهربائية والإنارة' },
      { en: 'Plumbing & drainage', ar: 'الأعمال الصحية والصرف' },
      { en: 'BMS, automation & smart metering', ar: 'إدارة المباني والأتمتة والعدادات الذكية' },
      { en: 'Low current & security', ar: 'التيار الخفيف والأنظمة الأمنية' },
      { en: 'Solar energy', ar: 'الطاقة الشمسية' },
      { en: 'UPS, generators & backup power', ar: 'وحدات UPS والمولدات والطاقة الاحتياطية' },
    ],
    facts: [
      [{ en: 'Experience', ar: 'الخبرة' }, { en: '20+ years', ar: 'أكثر من 20 عاماً' }],
      [{ en: 'Projects', ar: 'المشاريع' }, { en: '500+ completed', ar: 'أكثر من 500 مشروع' }],
      [{ en: 'Team', ar: 'الفريق' }, { en: '150+ engineers & technicians', ar: 'أكثر من 150 مهندساً وفنياً' }],
      [{ en: 'Coverage', ar: 'نطاق العمل' }, { en: 'Saudi Arabia & region', ar: 'السعودية والمنطقة' }],
      [{ en: 'Standards', ar: 'المعايير' }, { en: 'ASHRAE · NFPA · IEC · SMACNA', ar: 'ASHRAE · NFPA · IEC · SMACNA' }],
    ],
    processTitle: { en: 'Every stage, <em>one team</em>', ar: 'كل المراحل، <em>فريق واحد</em>' },
    processLead: {
      en: 'We can join at any stage — or carry the MEP package from first value review to long-term maintenance.',
      ar: 'يمكننا الانضمام في أي مرحلة، أو تولي الأعمال الكهروميكانيكية كاملة من مراجعة القيمة الأولى حتى الصيانة طويلة المدى.',
    },
    process: [
      { t: { en: 'Procurement', ar: 'المشتريات' }, d: { en: 'Value review, equipment selection, material submittals, procurement and inspection before delivery.', ar: 'مراجعة القيمة، واختيار المعدات، واعتماد المواد، والتوريد والفحص قبل التسليم.' } },
      { t: { en: 'Engineering drawings', ar: 'المخططات الهندسية' }, d: { en: 'Engineering calculations, shop drawings, sections and details, schematic and combined services drawings.', ar: 'الحسابات الهندسية، والمخططات التنفيذية والقطاعات والتفاصيل، والمخططات التخطيطية ومخططات تنسيق الخدمات.' } },
      { t: { en: 'Execution', ar: 'التنفيذ' }, d: { en: 'Method statements, installation, project management, testing and commissioning.', ar: 'خطط التنفيذ، والتركيب، وإدارة المشروع، والاختبار والتشغيل التجريبي.' } },
      { t: { en: 'Value engineering', ar: 'هندسة القيمة' }, d: { en: 'Optimised design, cost control, lifecycle cost analysis and constructability reviews.', ar: 'تحسين التصميم، وضبط التكاليف، وتحليل تكلفة دورة الحياة، ومراجعة قابلية التنفيذ.' } },
      { t: { en: 'Infrastructure M&E', ar: 'البنية التحتية الميكانيكية والكهربائية' }, d: { en: 'Mechanical and electrical infrastructure networks, plant and power storage.', ar: 'شبكات البنية التحتية الميكانيكية والكهربائية، والمحطات، وتخزين الطاقة.' } },
      { t: { en: 'Facility management', ar: 'إدارة المرافق' }, d: { en: 'Operation and maintenance that keeps every system performing after handover.', ar: 'تشغيل وصيانة تحافظ على كفاءة كل نظام بعد التسليم.' } },
    ],
    faq: [
      { q: { en: 'What does an MEP contractor do?', ar: 'ما دور مقاول الأعمال الكهروميكانيكية؟' }, a: { en: 'An MEP contractor designs, supplies, installs and commissions the mechanical, electrical and plumbing systems of a building — air conditioning, power, lighting, water, drainage and fire protection — and coordinates them with the structure and architecture. Barakat Arabia also maintains these systems after handover.', ar: 'يتولى مقاول الأعمال الكهروميكانيكية تصميم الأنظمة الميكانيكية والكهربائية والصحية للمبنى وتوريدها وتركيبها وتشغيلها، مثل التكييف والكهرباء والإنارة والمياه والصرف والحماية من الحريق، مع تنسيقها مع الأعمال الإنشائية والمعمارية. وتقدم البركات العربية أيضاً صيانة هذه الأنظمة بعد التسليم.' } },
      { q: { en: 'Where in Saudi Arabia do you work?', ar: 'في أي مناطق المملكة تعملون؟' }, a: { en: 'We deliver projects across the Kingdom, with activity centred on Riyadh and Jeddah, and have completed work in Egypt, Kenya and Libya.', ar: 'ننفذ مشاريع في مختلف مناطق المملكة، مع تركيز نشاطنا في الرياض وجدة، ولدينا أعمال منجزة في مصر وكينيا وليبيا.' } },
      { q: { en: 'Can you take on a single system instead of the full MEP package?', ar: 'هل يمكنكم تنفيذ نظام واحد فقط بدلاً من الحزمة الكاملة؟' }, a: { en: 'Yes. We regularly deliver individual packages such as HVAC, firefighting or BMS, as well as complete MEP scopes.', ar: 'نعم، ننفذ باستمرار حزماً منفصلة مثل التكييف أو مكافحة الحريق أو أنظمة إدارة المباني، إلى جانب نطاقات الأعمال الكهروميكانيكية الكاملة.' } },
      { q: { en: 'How do I request a proposal?', ar: 'كيف أطلب عرض سعر؟' }, a: { en: 'Send your drawings, BOQ or a short description of the project through the contact form, by WhatsApp on +966 54 412 6721 or by email to info@barakatarabia.com. Our team will review the scope and get back to you.', ar: 'أرسل المخططات أو جدول الكميات أو وصفاً مختصراً للمشروع عبر نموذج التواصل، أو واتساب على الرقم ‎+966 54 412 6721، أو البريد الإلكتروني info@barakatarabia.com، وسيراجع فريقنا النطاق ويتواصل معك.' } },
    ],
    related: ['misk-city-mobility-hub', 'dental-center-king-saud-medical-city', 'hilton-garden-inn-new-cairo', 'epc-vcm-alexandria'],
  },

  {
    slug: 'hvac-systems',
    icon: 'fan',
    img: { base: 'img/gallery-11', widths: [600, 1000, 1800] },
    imgAlt: { en: 'Rooftop air handling units', ar: 'وحدات مناولة هواء على السطح' },
    name: { en: 'HVAC Systems', ar: 'أنظمة التكييف والتهوية' },
    short: { en: 'HVAC & ventilation', ar: 'التكييف والتهوية' },
    card: { en: 'Chilled-water, VRF, air handling and ventilation systems.', ar: 'أنظمة المياه المبردة وVRF ومناولة الهواء والتهوية.' },
    seoTitle: { en: 'HVAC Contractor in Saudi Arabia | Barakat Arabia', ar: 'مقاول تكييف وتهوية في السعودية | البركات العربية' },
    desc: {
      en: 'HVAC contractor in Saudi Arabia: design, supply, installation and maintenance of chilled-water, VRF, air handling and ventilation systems.',
      ar: 'مقاول أنظمة تكييف وتهوية (HVAC) في السعودية: تصميم وتوريد وتركيب وصيانة أنظمة المياه المبردة وVRF ووحدات مناولة الهواء والتهوية.',
    },
    h1: { en: 'HVAC systems <em>built for the Saudi climate</em>', ar: 'أنظمة تكييف وتهوية <em>مصممة لمناخ المملكة</em>' },
    lead: {
      en: 'Design, supply, installation, testing and maintenance of heating, ventilation and air-conditioning systems for every type of building.',
      ar: 'تصميم أنظمة التدفئة والتهوية والتكييف وتوريدها وتركيبها واختبارها وصيانتها لجميع أنواع المباني.',
    },
    chips: [{ en: 'Chilled water', ar: 'المياه المبردة' }, { en: 'VRF', ar: 'VRF' }, { en: 'AHU & FCU', ar: 'AHU و FCU' }, { en: 'Ventilation', ar: 'التهوية' }],
    overview: [
      {
        en: 'Barakat Arabia designs, supplies, installs and maintains HVAC systems that keep buildings comfortable, healthy and energy-efficient through long, hot Saudi summers.',
        ar: 'تصمم البركات العربية أنظمة التكييف والتهوية وتوردها وتركّبها وتصونها، لتبقى المباني مريحة وصحية وموفرة للطاقة طوال فصول الصيف الطويلة والحارة في المملكة.',
      },
      {
        en: 'From central chilled-water plants and VRF systems to air handling units, ductwork and smoke-extract fans, our mechanical engineers and site teams deliver the complete package: heat-load calculations, shop drawings, equipment selection, installation, testing, adjusting and balancing, and commissioning. We have delivered HVAC works for healthcare, pharmaceutical, industrial and commercial buildings — including the Dental Center at King Saud Medical City in Riyadh, Tiba Pharma and the Procter & Gamble plant in 6th of October City.',
        ar: 'من محطات المياه المبردة المركزية وأنظمة VRF إلى وحدات مناولة الهواء ومجاري الهواء ومراوح شفط الدخان، ينفذ مهندسونا الميكانيكيون وفرقنا الميدانية الحزمة كاملة: حسابات الأحمال الحرارية، والمخططات التنفيذية، واختيار المعدات، والتركيب، والاختبار والموازنة (TAB)، والتشغيل التجريبي. وقد نفذنا أعمال تكييف لمبانٍ صحية ودوائية وصناعية وتجارية، منها مركز طب الأسنان بمدينة الملك سعود الطبية في الرياض، ومصنع طيبة فارما، ومصنع بروكتر آند جامبل في مدينة السادس من أكتوبر.',
      },
    ],
    scopeTitle: { en: 'What we deliver', ar: 'ما نقدمه' },
    scope: [
      { en: 'Central chilled-water plants', ar: 'محطات المياه المبردة المركزية' },
      { en: 'VRF and split systems', ar: 'أنظمة VRF والوحدات المنفصلة' },
      { en: 'Air handling & fan coil units', ar: 'وحدات مناولة الهواء ووحدات ملفات المراوح' },
      { en: 'Ductwork fabrication & installation', ar: 'تصنيع مجاري الهواء وتركيبها' },
      { en: 'Fresh-air & smoke-extract systems', ar: 'أنظمة الهواء النقي وشفط الدخان' },
      { en: 'Kitchen & toilet exhaust', ar: 'أنظمة شفط المطابخ ودورات المياه' },
      { en: 'Healthcare & pharma air quality', ar: 'جودة الهواء للمنشآت الصحية والدوائية' },
      { en: 'Testing, adjusting & balancing', ar: 'الاختبار والضبط والموازنة (TAB)' },
    ],
    facts: [
      [{ en: 'Systems', ar: 'الأنظمة' }, { en: 'Chilled water · VRF · AHU', ar: 'مياه مبردة · VRF · AHU' }],
      [{ en: 'Standards', ar: 'المعايير' }, { en: 'ASHRAE · SMACNA', ar: 'ASHRAE · SMACNA' }],
      [{ en: 'Sectors', ar: 'القطاعات' }, { en: 'Healthcare · Commercial · Industrial', ar: 'صحي · تجاري · صناعي' }],
      [{ en: 'Coverage', ar: 'نطاق العمل' }, { en: 'Riyadh · Jeddah · KSA', ar: 'الرياض · جدة · المملكة' }],
    ],
    process: [
      { t: { en: 'Design & load calculations', ar: 'التصميم وحساب الأحمال' }, d: { en: 'Heat-load calculations, equipment selection and coordinated shop drawings.', ar: 'حسابات الأحمال الحرارية، واختيار المعدات، ومخططات تنفيذية منسقة.' } },
      { t: { en: 'Submittals & procurement', ar: 'الاعتمادات والتوريد' }, d: { en: 'Material submittals and approved equipment, inspected before it reaches site.', ar: 'اعتماد المواد وتوريد معدات معتمدة يتم فحصها قبل وصولها إلى الموقع.' } },
      { t: { en: 'Installation', ar: 'التركيب' }, d: { en: 'Ductwork, piping, insulation and equipment installed by experienced HVAC crews.', ar: 'تركيب مجاري الهواء والأنابيب والعزل والمعدات بواسطة فرق تكييف ذات خبرة.' } },
      { t: { en: 'Commissioning & handover', ar: 'التشغيل والتسليم' }, d: { en: 'Pressure tests, TAB, commissioning, as-built drawings and O&M manuals.', ar: 'اختبارات الضغط، والموازنة، والتشغيل التجريبي، ومخططات ما تم تنفيذه وأدلة التشغيل والصيانة.' } },
    ],
    faq: [
      { q: { en: 'Which HVAC systems do you install?', ar: 'ما أنظمة التكييف التي تركبونها؟' }, a: { en: 'Central chilled-water systems, VRF and split systems, packaged units, air handling and fan coil units, and ventilation, exhaust and smoke-extract systems — for new buildings and for upgrades to existing ones.', ar: 'أنظمة المياه المبردة المركزية، وأنظمة VRF والوحدات المنفصلة، والوحدات المجمعة، ووحدات مناولة الهواء وملفات المراوح، وأنظمة التهوية والشفط وشفط الدخان، سواء للمباني الجديدة أو لتطوير المباني القائمة.' } },
      { q: { en: 'Do you work on hospitals and pharmaceutical facilities?', ar: 'هل تنفذون أعمالاً للمستشفيات والمنشآت الدوائية؟' }, a: { en: 'Yes. Our HVAC references include the Dental Center at King Saud Medical City in Riyadh and the Tiba Pharma and Badr Pharma facilities, where filtration, air changes and pressure control are critical.', ar: 'نعم، تشمل مراجعنا في التكييف مركز طب الأسنان بمدينة الملك سعود الطبية في الرياض ومنشآت طيبة فارما وبدر فارما، حيث تُعد الفلترة ومعدلات تغيير الهواء والتحكم في الضغط عناصر أساسية.' } },
      { q: { en: 'Do you maintain HVAC systems after handover?', ar: 'هل تقدمون صيانة لأنظمة التكييف بعد التسليم؟' }, a: { en: 'Yes. Through our MEP facility management service we provide planned preventive maintenance, breakdown response and performance checks for chillers, AHUs, VRF and ventilation systems.', ar: 'نعم، من خلال خدمة إدارة مرافق الأنظمة الكهروميكانيكية نقدم الصيانة الوقائية المخططة، والاستجابة للأعطال، وفحوص الأداء للمبردات ووحدات مناولة الهواء وأنظمة VRF والتهوية.' } },
      { q: { en: 'How do I get a quotation for HVAC works?', ar: 'كيف أحصل على عرض سعر لأعمال التكييف؟' }, a: { en: 'Share your drawings, BOQ or project brief through the contact form, WhatsApp or email. Our mechanical team will review the scope and respond with the next steps.', ar: 'شارك المخططات أو جدول الكميات أو وصف المشروع عبر نموذج التواصل أو واتساب أو البريد الإلكتروني، وسيراجع فريقنا الميكانيكي النطاق ويتواصل معك بالخطوات التالية.' } },
    ],
    related: ['dental-center-king-saud-medical-city', 'tiba-pharma-cairo', 'elsewedy-office-building', 'procter-gamble-6th-of-october'],
  },

  {
    slug: 'firefighting-fire-alarm-systems',
    icon: 'flame',
    img: { base: 'img/gallery-07', widths: [600, 1000, 1800] },
    imgAlt: { en: 'Firefighting pump room valves and pipework', ar: 'صمامات وأنابيب غرفة مضخات الحريق' },
    name: { en: 'Firefighting & Fire Alarm Systems', ar: 'أنظمة مكافحة الحريق وإنذار الحريق' },
    short: { en: 'Firefighting & fire alarm', ar: 'مكافحة الحريق والإنذار' },
    card: { en: 'Sprinklers, fire pumps, FM-200 and addressable fire alarm.', ar: 'الرشاشات ومضخات الحريق وFM-200 وأنظمة الإنذار المعنونة.' },
    seoTitle: { en: 'Firefighting & Fire Alarm Systems in KSA | Barakat Arabia', ar: 'مقاول أنظمة مكافحة وإنذار الحريق بالسعودية | البركات العربية' },
    desc: {
      en: 'Firefighting and fire alarm contractor in Saudi Arabia: sprinklers, fire pumps, FM-200 suppression, fire water tanks and addressable detection.',
      ar: 'مقاول أنظمة مكافحة الحريق وإنذار الحريق في السعودية: رشاشات تلقائية، مضخات حريق، إطفاء FM-200، خزانات مياه الحريق وأنظمة الكشف المعنونة.',
    },
    h1: { en: 'Fire protection <em>that performs when it matters</em>', ar: 'حماية من الحريق <em>تعمل حين تكون الحاجة إليها</em>' },
    lead: {
      en: 'Design, installation, testing and maintenance of firefighting, suppression and fire detection systems.',
      ar: 'تصميم أنظمة مكافحة الحريق والإطفاء وكشف الحريق وتركيبها واختبارها وصيانتها.',
    },
    chips: [{ en: 'Sprinklers', ar: 'الرشاشات' }, { en: 'Fire pumps', ar: 'مضخات الحريق' }, { en: 'FM-200', ar: 'FM-200' }, { en: 'Fire alarm', ar: 'إنذار الحريق' }],
    overview: [
      {
        en: 'Barakat Arabia installs and maintains the fire protection systems that keep occupants safe and buildings compliant — from sprinkler networks and fire pump rooms to gas suppression and addressable fire alarm.',
        ar: 'تركّب البركات العربية أنظمة الحماية من الحريق وتصونها لتحافظ على سلامة شاغلي المباني وتوافقها مع الاشتراطات، بدءاً من شبكات الرشاشات وغرف مضخات الحريق وصولاً إلى أنظمة الإطفاء بالغاز وأنظمة الإنذار المعنونة.',
      },
      {
        en: 'Our teams deliver the full scope: hydraulic calculations and shop drawings, fire pumps and controllers, sprinkler, standpipe and hose-reel networks, FM-200 and clean-agent suppression for critical rooms, and detection and alarm systems that interface with HVAC, lifts and BMS. We work to NFPA standards and prepare systems for inspection by the authority having jurisdiction. A dedicated fire water tank department supports every project, and our firefighting references include Cairo Capital Center, the GE Admin Building at Mivida, Tiba Pharma and Badr Pharma.',
        ar: 'تنفذ فرقنا النطاق كاملاً: الحسابات الهيدروليكية والمخططات التنفيذية، ومضخات الحريق ولوحات التحكم، وشبكات الرشاشات وخطوط الإطفاء وبكرات الخراطيم، وأنظمة الإطفاء FM-200 والغازات النظيفة للغرف الحساسة، وأنظمة الكشف والإنذار المرتبطة بأنظمة التكييف والمصاعد وإدارة المباني. نعمل وفق معايير NFPA ونجهّز الأنظمة لفحص الجهات المختصة. ويدعم كل مشروع قسم متخصص لخزانات مياه الحريق، ومن مراجعنا في مكافحة الحريق كايرو كابيتال سنتر ومبنى جنرال إلكتريك الإداري في ميفيدا وطيبة فارما وبدر فارما.',
      },
    ],
    scopeTitle: { en: 'What we deliver', ar: 'ما نقدمه' },
    scope: [
      { en: 'Automatic sprinkler systems', ar: 'أنظمة الرشاشات التلقائية' },
      { en: 'Fire pumps & pump rooms', ar: 'مضخات الحريق وغرف المضخات' },
      { en: 'Standpipes, hose reels & hydrants', ar: 'خطوط الإطفاء وبكرات الخراطيم والحنفيات' },
      { en: 'FM-200 & clean-agent suppression', ar: 'أنظمة الإطفاء FM-200 والغازات النظيفة' },
      { en: 'Fire water tanks', ar: 'خزانات مياه الحريق' },
      { en: 'Addressable fire detection & alarm', ar: 'أنظمة كشف وإنذار الحريق المعنونة' },
      { en: 'Voice evacuation systems', ar: 'أنظمة الإخلاء الصوتي' },
      { en: 'Inspection, testing & maintenance', ar: 'الفحص والاختبار والصيانة' },
    ],
    facts: [
      [{ en: 'Systems', ar: 'الأنظمة' }, { en: 'Sprinklers · Pumps · FM-200', ar: 'رشاشات · مضخات · FM-200' }],
      [{ en: 'Standards', ar: 'المعايير' }, { en: 'NFPA', ar: 'NFPA' }],
      [{ en: 'Specialist unit', ar: 'قسم متخصص' }, { en: 'Fire water tanks', ar: 'خزانات مياه الحريق' }],
      [{ en: 'Coverage', ar: 'نطاق العمل' }, { en: 'Riyadh · Jeddah · KSA', ar: 'الرياض · جدة · المملكة' }],
    ],
    process: [
      { t: { en: 'Design & calculations', ar: 'التصميم والحسابات' }, d: { en: 'Hydraulic calculations, device layouts and shop drawings for approval.', ar: 'الحسابات الهيدروليكية وتوزيع الأجهزة والمخططات التنفيذية للاعتماد.' } },
      { t: { en: 'Approved equipment', ar: 'معدات معتمدة' }, d: { en: 'Listed and approved pumps, valves, sprinklers and detection devices.', ar: 'مضخات وصمامات ورشاشات وأجهزة كشف مدرجة ومعتمدة.' } },
      { t: { en: 'Installation', ar: 'التركيب' }, d: { en: 'Pipework, pump rooms, tanks and alarm cabling installed and coordinated on site.', ar: 'تركيب الأنابيب وغرف المضخات والخزانات وكابلات الإنذار مع التنسيق في الموقع.' } },
      { t: { en: 'Testing & handover', ar: 'الاختبار والتسليم' }, d: { en: 'Flushing, pressure and flow tests, cause-and-effect testing and handover.', ar: 'الغسيل، واختبارات الضغط والتدفق، واختبار السيناريوهات، ثم التسليم.' } },
    ],
    faq: [
      { q: { en: 'Which standards do your fire protection systems follow?', ar: 'ما المعايير التي تتبعها أنظمة الحماية من الحريق لديكم؟' }, a: { en: 'Systems are designed and installed to NFPA standards and the project specification, and prepared for inspection and approval by the authority having jurisdiction.', ar: 'تُصمم الأنظمة وتُركّب وفق معايير NFPA ومواصفات المشروع، وتُجهّز لفحص الجهات المختصة واعتمادها.' } },
      { q: { en: 'Do you build fire water tanks?', ar: 'هل تنفذون خزانات مياه الحريق؟' }, a: { en: 'Yes. Barakat Arabia has a dedicated fire water tank department with its own supervisor, draftsman, fitters and helpers.', ar: 'نعم، لدى البركات العربية قسم متخصص لخزانات مياه الحريق يضم مشرفاً ورساماً هندسياً وفنيي تركيب ومساعدين.' } },
      { q: { en: 'Can the fire alarm connect to other building systems?', ar: 'هل يمكن ربط نظام إنذار الحريق بأنظمة المبنى الأخرى؟' }, a: { en: 'Yes. We integrate fire alarm panels with HVAC shutdown, smoke control, lift recall, access control and the building management system.', ar: 'نعم، نربط لوحات إنذار الحريق بإيقاف التكييف والتحكم في الدخان واستدعاء المصاعد والتحكم في الدخول ونظام إدارة المبنى.' } },
      { q: { en: 'Do you service existing fire systems?', ar: 'هل تقدمون خدمات للأنظمة القائمة؟' }, a: { en: 'Yes. We carry out inspection, testing and maintenance of existing sprinkler, pump, suppression and alarm systems, and upgrade systems that no longer meet requirements.', ar: 'نعم، ننفذ فحص واختبار وصيانة أنظمة الرشاشات والمضخات والإطفاء والإنذار القائمة، ونطوّر الأنظمة التي لم تعد تفي بالمتطلبات.' } },
    ],
    related: ['cairo-capital-center', 'ge-admin-building-mivida', 'tiba-pharma-cairo', 'epc-chairman-building-alexandria'],
  },

  {
    slug: 'electrical-power-lighting',
    icon: 'bolt',
    img: { base: 'img/gallery-12', widths: [600, 1000, 1800] },
    imgAlt: { en: 'Low-voltage electrical switchgear room', ar: 'غرفة لوحات توزيع كهربائية منخفضة الجهد' },
    name: { en: 'Electrical Power & Lighting', ar: 'القوى الكهربائية والإنارة' },
    short: { en: 'Electrical power & lighting', ar: 'القوى الكهربائية والإنارة' },
    card: { en: 'Switchgear, distribution, cabling, lighting and earthing.', ar: 'لوحات التوزيع والكابلات والإنارة والتأريض.' },
    seoTitle: { en: 'Electrical Contractor in Saudi Arabia | Barakat Arabia', ar: 'مقاول أعمال كهربائية في السعودية | البركات العربية' },
    desc: {
      en: 'Electrical contractor in Saudi Arabia: LV switchgear, distribution boards, cabling, containment, lighting, earthing and lightning protection.',
      ar: 'مقاول أعمال كهربائية في السعودية: لوحات الجهد المنخفض، ولوحات التوزيع، والكابلات، والإنارة، والتأريض، والحماية من الصواعق.',
    },
    h1: { en: 'Electrical power <em>and lighting systems</em>', ar: 'أنظمة القوى الكهربائية <em>والإنارة</em>' },
    lead: {
      en: 'Safe, reliable power distribution and lighting — engineered, installed, tested and maintained by one team.',
      ar: 'توزيع كهربائي وإنارة بأمان وموثوقية — تصميماً وتركيباً واختباراً وصيانة بفريق واحد.',
    },
    chips: [{ en: 'LV switchgear', ar: 'لوحات الجهد المنخفض' }, { en: 'Distribution', ar: 'التوزيع' }, { en: 'Lighting', ar: 'الإنارة' }, { en: 'Earthing', ar: 'التأريض' }],
    overview: [
      {
        en: 'Barakat Arabia delivers the electrical systems that power buildings and infrastructure — from main switchboards and distribution networks to lighting, small power and protection.',
        ar: 'تنفذ البركات العربية الأنظمة الكهربائية التي تغذي المباني ومشاريع البنية التحتية، من لوحات التوزيع الرئيسية وشبكات التوزيع إلى الإنارة والمخارج الكهربائية وأنظمة الحماية.',
      },
      {
        en: 'Our electrical engineers prepare load calculations, single-line diagrams and coordinated shop drawings, then our site teams install switchgear, distribution boards, cable containment, power cabling and interior and exterior lighting. Every installation is tested and documented before energisation, and we provide backup power, low-current and maintenance services so the whole electrical scope sits with one contractor. Our electrical references include Badr Pharma, where we delivered power and light-current systems, and the electromechanical works at Town Way Mall.',
        ar: 'يُعد مهندسونا الكهربائيون حسابات الأحمال والمخططات أحادية الخط والمخططات التنفيذية المنسقة، ثم تركّب فرقنا الميدانية لوحات الجهد المنخفض ولوحات التوزيع ومسارات الكابلات وكابلات القوى والإنارة الداخلية والخارجية. تُختبر كل الأعمال وتُوثّق قبل التشغيل، ونقدم كذلك خدمات الطاقة الاحتياطية والتيار الخفيف والصيانة، ليبقى النطاق الكهربائي كاملاً مع مقاول واحد. ومن مراجعنا الكهربائية مصنع بدر فارما، حيث نفذنا أعمال القوى الكهربائية والتيار الخفيف، والأعمال الكهروميكانيكية في تاون واي مول.',
      },
    ],
    scopeTitle: { en: 'What we deliver', ar: 'ما نقدمه' },
    scope: [
      { en: 'LV switchgear, MDBs & SMDBs', ar: 'لوحات الجهد المنخفض الرئيسية والفرعية' },
      { en: 'Final distribution boards', ar: 'لوحات التوزيع النهائية' },
      { en: 'Cable trays, trunking & conduits', ar: 'حوامل الكابلات والمجاري والمواسير' },
      { en: 'Power cabling & wiring', ar: 'كابلات القوى والتمديدات' },
      { en: 'Interior & exterior lighting', ar: 'الإنارة الداخلية والخارجية' },
      { en: 'Emergency & exit lighting', ar: 'إنارة الطوارئ ولوحات المخارج' },
      { en: 'Earthing & lightning protection', ar: 'التأريض والحماية من الصواعق' },
      { en: 'Infrastructure electrical works', ar: 'الأعمال الكهربائية للبنية التحتية' },
    ],
    facts: [
      [{ en: 'Systems', ar: 'الأنظمة' }, { en: 'Distribution · Lighting · Earthing', ar: 'توزيع · إنارة · تأريض' }],
      [{ en: 'Standards', ar: 'المعايير' }, { en: 'IEC · SASO', ar: 'IEC · SASO' }],
      [{ en: 'Sectors', ar: 'القطاعات' }, { en: 'Commercial · Industrial · Infrastructure', ar: 'تجاري · صناعي · بنية تحتية' }],
      [{ en: 'Coverage', ar: 'نطاق العمل' }, { en: 'Riyadh · Jeddah · KSA', ar: 'الرياض · جدة · المملكة' }],
    ],
    process: [
      { t: { en: 'Load studies & design', ar: 'دراسة الأحمال والتصميم' }, d: { en: 'Load calculations, cable sizing, single-line diagrams and shop drawings.', ar: 'حسابات الأحمال وتحديد مقاسات الكابلات والمخططات أحادية الخط والتنفيذية.' } },
      { t: { en: 'Procurement', ar: 'التوريد' }, d: { en: 'Switchgear, cables and luminaires submitted, approved and inspected.', ar: 'اعتماد وفحص اللوحات والكابلات ووحدات الإنارة قبل التوريد.' } },
      { t: { en: 'Installation', ar: 'التركيب' }, d: { en: 'Containment, cabling, boards and fittings installed to the approved drawings.', ar: 'تركيب المسارات والكابلات واللوحات والتجهيزات وفق المخططات المعتمدة.' } },
      { t: { en: 'Testing & energisation', ar: 'الاختبار والتشغيل' }, d: { en: 'Insulation, continuity and earth tests before safe energisation and handover.', ar: 'اختبارات العزل والاستمرارية والتأريض قبل التشغيل الآمن والتسليم.' } },
    ],
    faq: [
      { q: { en: 'What electrical works does Barakat Arabia carry out?', ar: 'ما الأعمال الكهربائية التي تنفذها البركات العربية؟' }, a: { en: 'LV switchgear and distribution, power cabling and containment, lighting and emergency lighting, earthing and lightning protection, and infrastructure electrical works — for new buildings, fit-outs and upgrades.', ar: 'لوحات الجهد المنخفض والتوزيع، وكابلات القوى ومساراتها، والإنارة وإنارة الطوارئ، والتأريض والحماية من الصواعق، والأعمال الكهربائية للبنية التحتية، سواء للمباني الجديدة أو أعمال التشطيب أو التطوير.' } },
      { q: { en: 'Do you also install generators and UPS?', ar: 'هل تركبون المولدات ووحدات UPS أيضاً؟' }, a: { en: 'Yes. Standby generators, ATS and synchronisation panels, UPS and battery systems are covered by our power backup service.', ar: 'نعم، تشمل خدمة الطاقة الاحتياطية لدينا المولدات الاحتياطية ولوحات التحويل التلقائي والمزامنة ووحدات UPS وأنظمة البطاريات.' } },
      { q: { en: 'Can you handle low-current systems in the same package?', ar: 'هل يمكن تنفيذ أنظمة التيار الخفيف ضمن الحزمة نفسها؟' }, a: { en: 'Yes. We deliver CCTV, access control, data networks and communication systems alongside the power scope, which simplifies coordination on site.', ar: 'نعم، ننفذ أنظمة المراقبة والتحكم في الدخول وشبكات البيانات والاتصالات إلى جانب أعمال القوى، مما يسهّل التنسيق في الموقع.' } },
      { q: { en: 'Do you provide electrical maintenance?', ar: 'هل تقدمون صيانة للأنظمة الكهربائية؟' }, a: { en: 'Yes. Our MEP facility management team provides preventive maintenance, thermal inspections and fault response for electrical installations.', ar: 'نعم، يقدم فريق إدارة المرافق لدينا الصيانة الوقائية والفحص الحراري والاستجابة للأعطال للتركيبات الكهربائية.' } },
    ],
    related: ['badr-pharma-cairo', 'town-way-mall-badr-city', 'epc-vcm-alexandria', 'jabco-admin-building-cairo'],
  },

  {
    slug: 'plumbing-drainage',
    icon: 'drop',
    img: { base: 'img/gallery-10', widths: [600, 1000, 1800] },
    imgAlt: { en: 'Pump set with insulated piping', ar: 'مجموعة مضخات بأنابيب معزولة' },
    name: { en: 'Plumbing & Drainage', ar: 'الأعمال الصحية والصرف' },
    short: { en: 'Plumbing & drainage', ar: 'الأعمال الصحية والصرف' },
    card: { en: 'Water supply, booster pumps, drainage and storm water.', ar: 'تغذية المياه ومضخات الرفع والصرف الصحي ومياه الأمطار.' },
    seoTitle: { en: 'Plumbing & Drainage Contractor in KSA | Barakat Arabia', ar: 'مقاول أعمال صحية وصرف في السعودية | البركات العربية' },
    desc: {
      en: 'Plumbing contractor in Saudi Arabia: water supply networks, tanks and booster pumps, water heating, sanitary and storm-water drainage.',
      ar: 'مقاول أعمال صحية في السعودية: شبكات تغذية المياه، والخزانات ومضخات الرفع، وتسخين المياه، والصرف الصحي وتصريف مياه الأمطار.',
    },
    h1: { en: 'Plumbing <em>and drainage systems</em>', ar: 'الأعمال الصحية <em>وأنظمة الصرف</em>' },
    lead: {
      en: 'Water supply, drainage and pumping systems that are efficient, hygienic and easy to maintain.',
      ar: 'أنظمة تغذية مياه وصرف وضخ فعّالة وصحية وسهلة الصيانة.',
    },
    chips: [{ en: 'Water supply', ar: 'تغذية المياه' }, { en: 'Booster pumps', ar: 'مضخات الرفع' }, { en: 'Drainage', ar: 'الصرف' }, { en: 'Storm water', ar: 'مياه الأمطار' }],
    overview: [
      {
        en: 'Barakat Arabia designs and installs plumbing and drainage systems for commercial, hospitality, healthcare and residential buildings — delivering reliable water supply and safe, odour-free drainage.',
        ar: 'تصمم البركات العربية أنظمة الأعمال الصحية والصرف وتركّبها للمباني التجارية والفندقية والصحية والسكنية، لتوفير إمداد مائي موثوق وصرف آمن خالٍ من الروائح.',
      },
      {
        en: 'Our scope covers cold and hot water networks, storage tanks and booster pump sets, water heaters including solar water heating, sanitary drainage and venting, and storm-water systems. We size pipework and pumps from hydraulic calculations, coordinate routes with the structure and other services, and pressure-test every network before handover. We also provide leak protection and maintenance so systems keep performing. Our plumbing references include Cairo Capital Center and the GE Admin Building at Mivida, New Cairo.',
        ar: 'يشمل نطاق عملنا شبكات المياه الباردة والساخنة، وخزانات التخزين ومجموعات مضخات الرفع، وسخانات المياه بما فيها التسخين الشمسي، والصرف الصحي والتهوية، وأنظمة تصريف مياه الأمطار. نحدد مقاسات الأنابيب والمضخات بناءً على الحسابات الهيدروليكية، وننسق المسارات مع الأعمال الإنشائية والخدمات الأخرى، ونختبر كل شبكة تحت الضغط قبل التسليم. كما نقدم حلول الحماية من التسربات والصيانة لضمان استمرار كفاءة الأنظمة. ومن مراجعنا في الأعمال الصحية كايرو كابيتال سنتر ومبنى جنرال إلكتريك الإداري في ميفيدا بالقاهرة الجديدة.',
      },
    ],
    scopeTitle: { en: 'What we deliver', ar: 'ما نقدمه' },
    scope: [
      { en: 'Cold & hot water networks', ar: 'شبكات المياه الباردة والساخنة' },
      { en: 'Water tanks & booster pumps', ar: 'خزانات المياه ومضخات الرفع' },
      { en: 'Water heaters & solar heating', ar: 'سخانات المياه والتسخين الشمسي' },
      { en: 'Sanitary drainage & venting', ar: 'الصرف الصحي والتهوية' },
      { en: 'Storm-water drainage', ar: 'تصريف مياه الأمطار' },
      { en: 'Sanitary fixtures installation', ar: 'تركيب الأدوات الصحية' },
      { en: 'Leak protection', ar: 'الحماية من التسربات' },
      { en: 'Infrastructure water networks', ar: 'شبكات المياه للبنية التحتية' },
    ],
    facts: [
      [{ en: 'Systems', ar: 'الأنظمة' }, { en: 'Water · Drainage · Pumps', ar: 'مياه · صرف · مضخات' }],
      [{ en: 'Standards', ar: 'المعايير' }, { en: 'ASTM · ASME', ar: 'ASTM · ASME' }],
      [{ en: 'Sectors', ar: 'القطاعات' }, { en: 'Commercial · Hospitality · Residential', ar: 'تجاري · فندقي · سكني' }],
      [{ en: 'Coverage', ar: 'نطاق العمل' }, { en: 'Riyadh · Jeddah · KSA', ar: 'الرياض · جدة · المملكة' }],
    ],
    process: [
      { t: { en: 'Hydraulic design', ar: 'التصميم الهيدروليكي' }, d: { en: 'Demand calculations, pipe and pump sizing and coordinated shop drawings.', ar: 'حساب الاستهلاك وتحديد مقاسات الأنابيب والمضخات ومخططات تنفيذية منسقة.' } },
      { t: { en: 'Materials & submittals', ar: 'المواد والاعتمادات' }, d: { en: 'Pipes, fittings, pumps and fixtures submitted and approved before supply.', ar: 'اعتماد الأنابيب والقطع والمضخات والأدوات الصحية قبل التوريد.' } },
      { t: { en: 'Installation', ar: 'التركيب' }, d: { en: 'Networks, tanks, pump sets and fixtures installed by skilled plumbers and fitters.', ar: 'تركيب الشبكات والخزانات والمضخات والأدوات بواسطة فنيين مهرة.' } },
      { t: { en: 'Testing & handover', ar: 'الاختبار والتسليم' }, d: { en: 'Pressure, flow and flushing tests, disinfection and as-built documentation.', ar: 'اختبارات الضغط والتدفق والغسيل، والتعقيم، وتوثيق ما تم تنفيذه.' } },
    ],
    faq: [
      { q: { en: 'What plumbing works do you deliver?', ar: 'ما أعمال السباكة التي تنفذونها؟' }, a: { en: 'Water supply networks, tanks and booster pumps, hot water and solar water heating, sanitary and storm-water drainage, fixtures installation and leak protection, for new buildings and renovations.', ar: 'شبكات تغذية المياه، والخزانات ومضخات الرفع، والمياه الساخنة والتسخين الشمسي، والصرف الصحي وتصريف مياه الأمطار، وتركيب الأدوات الصحية، والحماية من التسربات، للمباني الجديدة وأعمال التجديد.' } },
      { q: { en: 'Do you install water booster pump sets?', ar: 'هل تركبون مجموعات مضخات رفع المياه؟' }, a: { en: 'Yes. We select, install and commission booster and transfer pump sets and their controls, sized to the building’s demand.', ar: 'نعم، نختار مجموعات مضخات الرفع والنقل ولوحات التحكم الخاصة بها ونركّبها ونشغّلها بما يتناسب مع احتياج المبنى.' } },
      { q: { en: 'Do you work on hotels and residential towers?', ar: 'هل تعملون على الفنادق والأبراج السكنية؟' }, a: { en: 'Yes. Our MEP projects include the Hilton Garden Inn in New Cairo and residential towers in Nairobi, where reliable water supply and drainage are essential.', ar: 'نعم، تشمل مشاريعنا الكهروميكانيكية فندق هيلتون جاردن إن في القاهرة الجديدة وأبراجاً سكنية في نيروبي، حيث تُعد موثوقية تغذية المياه والصرف أمراً أساسياً.' } },
      { q: { en: 'Can you maintain existing plumbing systems?', ar: 'هل تقدمون صيانة لأنظمة السباكة القائمة؟' }, a: { en: 'Yes. Our facility management team maintains pumps, tanks, heaters and drainage networks and responds to leaks and blockages.', ar: 'نعم، يصون فريق إدارة المرافق المضخات والخزانات والسخانات وشبكات الصرف، ويستجيب للتسربات والانسدادات.' } },
    ],
    related: ['cairo-capital-center', 'ge-admin-building-mivida', 'hilton-garden-inn-new-cairo', 'wilma-towers-nairobi'],
  },

  {
    slug: 'bms-automation-smart-metering',
    icon: 'chip',
    img: { base: 'img/gallery-05', widths: [600, 1000, 1800] },
    imgAlt: { en: 'Electrical control panel with indicator lights', ar: 'لوحة تحكم كهربائية بمؤشرات تشغيل' },
    name: { en: 'BMS, Automation & Smart Metering', ar: 'إدارة المباني والأتمتة والعدادات الذكية' },
    short: { en: 'BMS & automation', ar: 'إدارة المباني والأتمتة' },
    card: { en: 'Building management, controls, IoT and smart metering.', ar: 'إدارة المباني وأنظمة التحكم وإنترنت الأشياء والعدادات الذكية.' },
    seoTitle: { en: 'BMS & Building Automation in Saudi Arabia | Barakat Arabia', ar: 'أنظمة إدارة المباني BMS والأتمتة بالسعودية | البركات العربية' },
    desc: {
      en: 'BMS contractor in Saudi Arabia: building management systems, HVAC and lighting controls, IoT integration, energy monitoring and smart metering.',
      ar: 'أنظمة إدارة المباني (BMS) في السعودية: التحكم في التكييف والإنارة، وتكامل إنترنت الأشياء، ومراقبة استهلاك الطاقة، والعدادات الذكية للكهرباء والمياه.',
    },
    h1: { en: 'Smarter buildings <em>with BMS and automation</em>', ar: 'مبانٍ أذكى <em>بأنظمة الإدارة والأتمتة</em>' },
    lead: {
      en: 'Monitor, control and optimise every building system from one place — and see exactly where energy and water go.',
      ar: 'راقب جميع أنظمة المبنى وتحكم فيها وحسّن أداءها من مكان واحد، واعرف بدقة أين يُستهلك كل من الطاقة والمياه.',
    },
    chips: [{ en: 'BMS', ar: 'BMS' }, { en: 'IoT', ar: 'إنترنت الأشياء' }, { en: 'Energy monitoring', ar: 'مراقبة الطاقة' }, { en: 'Smart metering', ar: 'العدادات الذكية' }],
    overview: [
      {
        en: 'Barakat Arabia delivers building management systems, automation and smart metering that give owners and facility teams real-time control and measurable energy savings.',
        ar: 'تنفذ البركات العربية أنظمة إدارة المباني والأتمتة والعدادات الذكية التي تمنح الملاك وفرق إدارة المرافق تحكماً فورياً ووفراً ملموساً في استهلاك الطاقة.',
      },
      {
        en: 'We engineer the points list and control strategy, install field devices, controllers and networks, and integrate HVAC plant, lighting, pumps, generators, fire alarm and lifts into a single operator interface. Smart power and water meters feed dashboards and reports so consumption can be tracked by floor, tenant or system. Because our teams also install the mechanical and electrical systems being controlled, commissioning is faster and interfaces are cleaner. Our BMS references include Tiba Pharma, the Nile-66 Admin Building and the Elsewedy Electric office building.',
        ar: 'نُعد قائمة النقاط واستراتيجية التحكم، ونركّب الأجهزة الميدانية ووحدات التحكم والشبكات، ونربط محطات التكييف والإنارة والمضخات والمولدات وإنذار الحريق والمصاعد في واجهة تشغيل واحدة. وتغذي العدادات الذكية للكهرباء والمياه لوحات المتابعة والتقارير لتتبع الاستهلاك حسب الطابق أو المستأجر أو النظام. ولأن فرقنا تركّب أيضاً الأنظمة الميكانيكية والكهربائية التي يتم التحكم فيها، يكون التشغيل التجريبي أسرع والربط أكثر دقة. ومن مراجعنا في أنظمة إدارة المباني طيبة فارما ومبنى نايل-66 الإداري ومبنى مكاتب السويدي إليكتريك.',
      },
    ],
    scopeTitle: { en: 'What we deliver', ar: 'ما نقدمه' },
    scope: [
      { en: 'Building management systems (BMS)', ar: 'أنظمة إدارة المباني (BMS)' },
      { en: 'HVAC & central plant controls', ar: 'التحكم في التكييف والمحطات المركزية' },
      { en: 'Lighting control systems', ar: 'أنظمة التحكم في الإنارة' },
      { en: 'IoT sensors & connected devices', ar: 'حساسات وأجهزة إنترنت الأشياء' },
      { en: 'Smart power & water metering', ar: 'العدادات الذكية للكهرباء والمياه' },
      { en: 'Energy monitoring dashboards', ar: 'لوحات مراقبة استهلاك الطاقة' },
      { en: 'Fire alarm, lift & security integration', ar: 'الربط مع الإنذار والمصاعد والأمن' },
      { en: 'Programming & operator training', ar: 'البرمجة وتدريب المشغلين' },
    ],
    facts: [
      [{ en: 'Systems', ar: 'الأنظمة' }, { en: 'BMS · IoT · Metering', ar: 'BMS · إنترنت الأشياء · عدادات' }],
      [{ en: 'Integrates', ar: 'يتكامل مع' }, { en: 'HVAC · Lighting · Fire · Lifts', ar: 'التكييف · الإنارة · الحريق · المصاعد' }],
      [{ en: 'Sectors', ar: 'القطاعات' }, { en: 'Commercial · Healthcare · Pharma', ar: 'تجاري · صحي · دوائي' }],
      [{ en: 'Coverage', ar: 'نطاق العمل' }, { en: 'Riyadh · Jeddah · KSA', ar: 'الرياض · جدة · المملكة' }],
    ],
    process: [
      { t: { en: 'Control strategy', ar: 'استراتيجية التحكم' }, d: { en: 'Points schedules, sequences of operation and network architecture.', ar: 'جداول النقاط وتسلسلات التشغيل وبنية الشبكة.' } },
      { t: { en: 'Hardware & software', ar: 'المعدات والبرمجيات' }, d: { en: 'Controllers, sensors, meters and head-end software submitted for approval.', ar: 'اعتماد وحدات التحكم والحساسات والعدادات وبرمجيات التشغيل المركزية.' } },
      { t: { en: 'Installation & integration', ar: 'التركيب والربط' }, d: { en: 'Field devices, cabling and panels installed and integrated with each system.', ar: 'تركيب الأجهزة الميدانية والكابلات واللوحات وربطها بكل نظام.' } },
      { t: { en: 'Commissioning & training', ar: 'التشغيل والتدريب' }, d: { en: 'Point-to-point testing, graphics, trend logs and operator training.', ar: 'اختبار النقاط، والواجهات الرسومية، وسجلات المتابعة، وتدريب المشغلين.' } },
    ],
    faq: [
      { q: { en: 'What is a building management system?', ar: 'ما نظام إدارة المباني؟' }, a: { en: 'A BMS is a computer-based control system that monitors and controls a building’s mechanical and electrical equipment — air conditioning, ventilation, lighting, pumps and power — to improve comfort, reduce energy use and alert operators to faults.', ar: 'نظام إدارة المباني نظام تحكم حاسوبي يراقب المعدات الميكانيكية والكهربائية في المبنى ويتحكم فيها، مثل التكييف والتهوية والإنارة والمضخات والطاقة، بهدف رفع مستوى الراحة وخفض استهلاك الطاقة وتنبيه المشغلين إلى الأعطال.' } },
      { q: { en: 'Can a BMS be added to an existing building?', ar: 'هل يمكن إضافة نظام إدارة مبانٍ لمبنى قائم؟' }, a: { en: 'Yes. We survey existing equipment, add controllers, sensors and meters where needed, and integrate the systems into a new or upgraded BMS with minimal disruption.', ar: 'نعم، نحصر المعدات القائمة، ونضيف وحدات التحكم والحساسات والعدادات حيث يلزم، ونربط الأنظمة بنظام إدارة جديد أو مطوّر بأقل قدر من التعطيل.' } },
      { q: { en: 'What does smart metering add?', ar: 'ما الذي تضيفه العدادات الذكية؟' }, a: { en: 'Smart power and water meters measure consumption continuously, so you can bill tenants accurately, spot leaks and waste early and verify energy-saving measures.', ar: 'تقيس العدادات الذكية للكهرباء والمياه الاستهلاك بشكل مستمر، مما يتيح محاسبة المستأجرين بدقة، واكتشاف التسربات والهدر مبكراً، والتحقق من نتائج إجراءات ترشيد الطاقة.' } },
      { q: { en: 'Do you provide BMS support after handover?', ar: 'هل تقدمون دعماً لنظام إدارة المباني بعد التسليم؟' }, a: { en: 'Yes. We offer operator training, software updates, re-tuning of control sequences and ongoing maintenance through our facility management service.', ar: 'نعم، نقدم تدريب المشغلين وتحديثات البرمجيات وإعادة ضبط تسلسلات التحكم والصيانة المستمرة ضمن خدمة إدارة المرافق.' } },
    ],
    related: ['tiba-pharma-cairo', 'nile-66-admin-building', 'elsewedy-office-building', 'misk-city-mobility-hub'],
  },

  {
    slug: 'low-current-security-systems',
    icon: 'shield',
    img: { base: 'img/gallery-04', widths: [600, 1000, 1800] },
    imgAlt: { en: 'Glass-façade administrative building', ar: 'مبنى إداري بواجهة زجاجية' },
    name: { en: 'Low Current & Security Systems', ar: 'أنظمة التيار الخفيف والأمن' },
    short: { en: 'Low current & security', ar: 'التيار الخفيف والأمن' },
    card: { en: 'CCTV, access control, data networks and communications.', ar: 'كاميرات المراقبة والتحكم في الدخول وشبكات البيانات والاتصالات.' },
    seoTitle: { en: 'Low Current & Security Systems in KSA | Barakat Arabia', ar: 'أنظمة التيار الخفيف والأنظمة الأمنية بالسعودية | البركات العربية' },
    desc: {
      en: 'Low-current contractor in Saudi Arabia: CCTV, access control, intercom, structured cabling, data networks, public address and communication systems.',
      ar: 'مقاول أنظمة التيار الخفيف في السعودية: كاميرات المراقبة، والتحكم في الدخول، والإنتركم، والكابلات الهيكلية، وشبكات البيانات، والنداء العام والاتصالات.',
    },
    h1: { en: 'Low current, security <em>and communications</em>', ar: 'التيار الخفيف والأمن <em>والاتصالات</em>' },
    lead: {
      en: 'The networks that keep buildings secure, connected and informed — designed, installed and integrated by our electrical team.',
      ar: 'الشبكات التي تحافظ على أمن المباني واتصالها — تصميماً وتركيباً وربطاً بواسطة فريقنا الكهربائي.',
    },
    chips: [{ en: 'CCTV', ar: 'كاميرات المراقبة' }, { en: 'Access control', ar: 'التحكم في الدخول' }, { en: 'Data networks', ar: 'شبكات البيانات' }, { en: 'Public address', ar: 'النداء العام' }],
    overview: [
      {
        en: 'Barakat Arabia installs low-current and security systems that protect people and assets and keep buildings connected — for offices, hotels, healthcare, industrial and residential projects.',
        ar: 'تركّب البركات العربية أنظمة التيار الخفيف والأنظمة الأمنية التي تحمي الأشخاص والممتلكات وتبقي المباني متصلة، للمكاتب والفنادق والمنشآت الصحية والصناعية والمشاريع السكنية.',
      },
      {
        en: 'Our scope includes IP CCTV surveillance, access control and video intercom, intrusion alarms, structured cabling and data networks, telephone and communication systems, public address and background music, and MATV/IPTV. We plan containment and cabling together with the power installation, so low-current routes are coordinated from the start, and we integrate security systems with fire alarm and the BMS. Our light-current references include Badr Pharma in Cairo.',
        ar: 'يشمل نطاق عملنا أنظمة المراقبة بالكاميرات الشبكية، والتحكم في الدخول والإنتركم المرئي، وأنظمة إنذار التسلل، والكابلات الهيكلية وشبكات البيانات، وأنظمة الهاتف والاتصالات، والنداء العام والصوتيات، وأنظمة الهوائي المركزي والتلفزيون الشبكي. نخطط مسارات الكابلات بالتزامن مع أعمال القوى الكهربائية لتكون مسارات التيار الخفيف منسقة منذ البداية، ونربط الأنظمة الأمنية بإنذار الحريق ونظام إدارة المبنى. ومن مراجعنا في أعمال التيار الخفيف مصنع بدر فارما بالقاهرة.',
      },
    ],
    scopeTitle: { en: 'What we deliver', ar: 'ما نقدمه' },
    scope: [
      { en: 'IP CCTV surveillance', ar: 'المراقبة بالكاميرات الشبكية' },
      { en: 'Access control & video intercom', ar: 'التحكم في الدخول والإنتركم المرئي' },
      { en: 'Intrusion & security alarms', ar: 'أنظمة إنذار التسلل والإنذار الأمني' },
      { en: 'Structured cabling & data networks', ar: 'الكابلات الهيكلية وشبكات البيانات' },
      { en: 'Telephone & communication systems', ar: 'أنظمة الهاتف والاتصالات' },
      { en: 'Public address & background music', ar: 'النداء العام والموسيقى الخلفية' },
      { en: 'MATV & IPTV systems', ar: 'أنظمة الهوائي المركزي والتلفزيون الشبكي' },
      { en: 'Integration with fire alarm & BMS', ar: 'الربط مع إنذار الحريق وإدارة المباني' },
    ],
    facts: [
      [{ en: 'Systems', ar: 'الأنظمة' }, { en: 'CCTV · Access · Networks', ar: 'مراقبة · دخول · شبكات' }],
      [{ en: 'Integrates', ar: 'يتكامل مع' }, { en: 'Fire alarm · BMS', ar: 'إنذار الحريق · BMS' }],
      [{ en: 'Sectors', ar: 'القطاعات' }, { en: 'Commercial · Hospitality · Industrial', ar: 'تجاري · فندقي · صناعي' }],
      [{ en: 'Coverage', ar: 'نطاق العمل' }, { en: 'Riyadh · Jeddah · KSA', ar: 'الرياض · جدة · المملكة' }],
    ],
    process: [
      { t: { en: 'Survey & design', ar: 'الحصر والتصميم' }, d: { en: 'Camera coverage, access zones, rack locations and cabling design.', ar: 'تغطية الكاميرات، ومناطق التحكم في الدخول، ومواقع الخزائن، وتصميم الكابلات.' } },
      { t: { en: 'Equipment approval', ar: 'اعتماد المعدات' }, d: { en: 'Cameras, controllers, network hardware and software submitted for approval.', ar: 'اعتماد الكاميرات ووحدات التحكم ومعدات الشبكات والبرمجيات.' } },
      { t: { en: 'Installation', ar: 'التركيب' }, d: { en: 'Containment, cabling, devices and racks installed and labelled.', ar: 'تركيب المسارات والكابلات والأجهزة والخزائن مع ترقيمها.' } },
      { t: { en: 'Testing & training', ar: 'الاختبار والتدريب' }, d: { en: 'Cable certification, system programming, integration tests and training.', ar: 'اعتماد الكابلات، وبرمجة الأنظمة، واختبارات الربط، والتدريب.' } },
    ],
    faq: [
      { q: { en: 'What are low-current systems?', ar: 'ما المقصود بأنظمة التيار الخفيف؟' }, a: { en: 'Low-current (light-current) systems are the extra-low-voltage networks in a building — CCTV, access control, fire alarm, data and telephone networks, public address and TV distribution.', ar: 'أنظمة التيار الخفيف هي الشبكات منخفضة الجهد جداً في المبنى، مثل كاميرات المراقبة والتحكم في الدخول وإنذار الحريق وشبكات البيانات والهاتف والنداء العام وتوزيع البث التلفزيوني.' } },
      { q: { en: 'Can you integrate CCTV and access control with other systems?', ar: 'هل يمكن ربط المراقبة والتحكم في الدخول بالأنظمة الأخرى؟' }, a: { en: 'Yes. We integrate security systems with the fire alarm, so doors release on alarm, and with the BMS for central monitoring.', ar: 'نعم، نربط الأنظمة الأمنية بنظام إنذار الحريق لفتح الأبواب تلقائياً عند الإنذار، وبنظام إدارة المبنى للمراقبة المركزية.' } },
      { q: { en: 'Do you install data networks and structured cabling?', ar: 'هل تنفذون شبكات البيانات والكابلات الهيكلية؟' }, a: { en: 'Yes. We install copper and fibre structured cabling, racks and network infrastructure, and test and certify every link.', ar: 'نعم، ننفذ الكابلات الهيكلية النحاسية والألياف الضوئية والخزائن والبنية التحتية للشبكات، ونختبر كل وصلة ونعتمدها.' } },
      { q: { en: 'Do you maintain security systems?', ar: 'هل تقدمون صيانة للأنظمة الأمنية؟' }, a: { en: 'Yes. We provide preventive maintenance, firmware updates and repairs for CCTV, access control and communication systems.', ar: 'نعم، نقدم الصيانة الوقائية وتحديثات البرامج والإصلاحات لأنظمة المراقبة والتحكم في الدخول والاتصالات.' } },
    ],
    related: ['badr-pharma-cairo', 'epc-chairman-building-alexandria', 'misk-city-mobility-hub', 'hilton-garden-inn-new-cairo'],
  },

  {
    slug: 'solar-energy',
    icon: 'solar',
    img: { base: 'img/gallery-09', widths: [600, 1000, 1800] },
    imgAlt: { en: 'Pharmaceutical facility exterior', ar: 'واجهة منشأة دوائية' },
    name: { en: 'Solar Energy Solutions', ar: 'حلول الطاقة الشمسية' },
    short: { en: 'Solar energy', ar: 'الطاقة الشمسية' },
    card: { en: 'Rooftop PV, hybrid systems, storage and solar water heating.', ar: 'ألواح شمسية على الأسطح وأنظمة هجينة وتخزين وتسخين شمسي.' },
    seoTitle: { en: 'Solar Energy Solutions in Saudi Arabia | Barakat Arabia', ar: 'حلول الطاقة الشمسية في السعودية | البركات العربية' },
    desc: {
      en: 'Solar energy contractor in Saudi Arabia: rooftop and carport PV, on-grid and hybrid systems, battery storage, solar water heating and maintenance.',
      ar: 'حلول الطاقة الشمسية في السعودية: أنظمة كهروضوئية على الأسطح والمظلات، وأنظمة متصلة بالشبكة وهجينة، وتخزين بالبطاريات، وتسخين المياه بالطاقة الشمسية.',
    },
    h1: { en: 'Solar energy <em>for lower-cost, cleaner power</em>', ar: 'الطاقة الشمسية <em>لكهرباء أنظف وأقل تكلفة</em>' },
    lead: {
      en: 'Solar PV and solar water heating systems, integrated with your building’s electrical and mechanical services.',
      ar: 'أنظمة كهروضوئية وأنظمة تسخين مياه بالطاقة الشمسية، متكاملة مع الخدمات الكهربائية والميكانيكية لمبناك.',
    },
    chips: [{ en: 'Rooftop PV', ar: 'ألواح الأسطح' }, { en: 'Hybrid systems', ar: 'أنظمة هجينة' }, { en: 'Battery storage', ar: 'تخزين البطاريات' }, { en: 'Solar water heating', ar: 'التسخين الشمسي' }],
    overview: [
      {
        en: 'Saudi Arabia has some of the strongest solar resources in the world. Barakat Arabia helps building owners turn that sunlight into lower energy bills with solar systems engineered as part of the wider MEP installation.',
        ar: 'تمتلك المملكة العربية السعودية من أعلى معدلات الإشعاع الشمسي في العالم، وتساعد البركات العربية ملاك المباني على تحويل هذه الطاقة إلى فواتير كهرباء أقل عبر أنظمة شمسية مصممة ضمن منظومة الأعمال الكهروميكانيكية المتكاملة.',
      },
      {
        en: 'We assess roof and carport areas and energy consumption, size PV arrays, inverters and battery storage, and connect the system safely to the building’s distribution boards, with protection and metering in place. For hot water, solar water heaters reduce electrical load in hotels, residences and healthcare buildings. Because the same team handles electrical power, backup generation and BMS, solar output can be monitored and combined with grid and generator supplies. We also provide cleaning and preventive maintenance to keep performance high in dusty conditions.',
        ar: 'نقيّم مساحات الأسطح والمظلات واستهلاك الطاقة، ونحدد قدرات الألواح والعواكس وبطاريات التخزين، ونربط النظام بأمان بلوحات توزيع المبنى مع أنظمة الحماية والقياس. أما للمياه الساخنة، فتخفض السخانات الشمسية الحمل الكهربائي في الفنادق والمباني السكنية والمنشآت الصحية. ولأن الفريق نفسه يتولى أعمال القوى الكهربائية والتوليد الاحتياطي وإدارة المباني، يمكن مراقبة إنتاج الطاقة الشمسية ودمجه مع مصادر الشبكة والمولدات. كما نقدم خدمات التنظيف والصيانة الوقائية للحفاظ على كفاءة الأداء في الظروف المغبرة.',
      },
    ],
    scopeTitle: { en: 'What we deliver', ar: 'ما نقدمه' },
    scope: [
      { en: 'Rooftop & carport solar PV', ar: 'ألواح كهروضوئية على الأسطح والمظلات' },
      { en: 'On-grid, off-grid & hybrid systems', ar: 'أنظمة متصلة ومستقلة وهجينة' },
      { en: 'Inverters, protection & metering', ar: 'العواكس والحماية والقياس' },
      { en: 'Battery energy storage', ar: 'تخزين الطاقة بالبطاريات' },
      { en: 'Solar water heating', ar: 'تسخين المياه بالطاقة الشمسية' },
      { en: 'Integration with building power', ar: 'الربط مع كهرباء المبنى' },
      { en: 'Performance monitoring', ar: 'مراقبة الأداء' },
      { en: 'Cleaning & maintenance', ar: 'التنظيف والصيانة' },
    ],
    facts: [
      [{ en: 'Systems', ar: 'الأنظمة' }, { en: 'PV · Storage · Solar heating', ar: 'كهروضوئية · تخزين · تسخين' }],
      [{ en: 'Integrates', ar: 'يتكامل مع' }, { en: 'Distribution · Generators · BMS', ar: 'التوزيع · المولدات · BMS' }],
      [{ en: 'Sectors', ar: 'القطاعات' }, { en: 'Commercial · Residential · Industrial', ar: 'تجاري · سكني · صناعي' }],
      [{ en: 'Coverage', ar: 'نطاق العمل' }, { en: 'Riyadh · Jeddah · KSA', ar: 'الرياض · جدة · المملكة' }],
    ],
    process: [
      { t: { en: 'Site & energy assessment', ar: 'تقييم الموقع والطاقة' }, d: { en: 'Roof survey, shading review and analysis of consumption and tariffs.', ar: 'حصر الأسطح ودراسة التظليل وتحليل الاستهلاك والتعرفة.' } },
      { t: { en: 'System design', ar: 'تصميم النظام' }, d: { en: 'Array, inverter and storage sizing with structural and electrical design.', ar: 'تحديد قدرات الألواح والعواكس والتخزين مع التصميم الإنشائي والكهربائي.' } },
      { t: { en: 'Installation', ar: 'التركيب' }, d: { en: 'Mounting structures, modules, cabling, inverters and protection installed.', ar: 'تركيب الهياكل والألواح والكابلات والعواكس وأنظمة الحماية.' } },
      { t: { en: 'Commissioning & monitoring', ar: 'التشغيل والمراقبة' }, d: { en: 'Testing, grid connection coordination, monitoring set-up and handover.', ar: 'الاختبار، وتنسيق الربط بالشبكة، وإعداد المراقبة، والتسليم.' } },
    ],
    faq: [
      { q: { en: 'Is solar worthwhile for buildings in Saudi Arabia?', ar: 'هل الطاقة الشمسية مجدية للمباني في السعودية؟' }, a: { en: 'Solar irradiation in the Kingdom is among the highest in the world, so a well-designed PV system can cover a meaningful share of daytime electrical load. We assess your roof, consumption and tariff before recommending a system size.', ar: 'يُعد الإشعاع الشمسي في المملكة من الأعلى عالمياً، لذا يمكن لنظام كهروضوئي مصمم جيداً أن يغطي جزءاً كبيراً من الأحمال الكهربائية النهارية. نقيّم السطح والاستهلاك والتعرفة قبل التوصية بقدرة النظام.' } },
      { q: { en: 'What is the difference between on-grid and hybrid systems?', ar: 'ما الفرق بين الأنظمة المتصلة بالشبكة والأنظمة الهجينة؟' }, a: { en: 'An on-grid system works alongside the utility supply. A hybrid system adds battery storage and can work with generators, keeping critical loads running during outages.', ar: 'يعمل النظام المتصل بالشبكة جنباً إلى جنب مع كهرباء الشبكة العامة، بينما يضيف النظام الهجين بطاريات تخزين ويمكنه العمل مع المولدات للحفاظ على تشغيل الأحمال الحرجة أثناء الانقطاعات.' } },
      { q: { en: 'Do you install solar water heaters?', ar: 'هل تركبون سخانات المياه الشمسية؟' }, a: { en: 'Yes. Solar water heating is delivered as part of our plumbing scope for hotels, residential buildings and other facilities with high hot-water demand.', ar: 'نعم، ننفذ أنظمة تسخين المياه بالطاقة الشمسية ضمن نطاق الأعمال الصحية للفنادق والمباني السكنية والمنشآت ذات الطلب المرتفع على المياه الساخنة.' } },
      { q: { en: 'How are solar panels maintained in dusty conditions?', ar: 'كيف تتم صيانة الألواح الشمسية في الأجواء المغبرة؟' }, a: { en: 'Regular panel cleaning, inspection of connections and inverter checks keep output high. We offer these as scheduled maintenance.', ar: 'يحافظ التنظيف الدوري للألواح وفحص التوصيلات والعواكس على ارتفاع الإنتاج، ونقدم ذلك ضمن برامج صيانة مجدولة.' } },
    ],
    related: ['misk-city-mobility-hub', 'grand-premiere-towers-nairobi', 'wilma-towers-nairobi', 'town-way-mall-badr-city'],
  },

  {
    slug: 'power-backup-ups-generators',
    icon: 'battery',
    img: { base: 'img/gallery-06', widths: [600, 1000, 1800] },
    imgAlt: { en: 'Standby diesel generator and control module', ar: 'مولد ديزل احتياطي ووحدة التحكم' },
    name: { en: 'Power Backup: UPS & Generators', ar: 'الطاقة الاحتياطية: UPS والمولدات' },
    short: { en: 'UPS & generators', ar: 'UPS والمولدات' },
    card: { en: 'Standby generators, ATS, synchronisation, UPS and batteries.', ar: 'المولدات الاحتياطية ولوحات التحويل والمزامنة وUPS والبطاريات.' },
    seoTitle: { en: 'UPS, Generators & Backup Power in KSA | Barakat Arabia', ar: 'المولدات ووحدات UPS والطاقة الاحتياطية بالسعودية | البركات العربية' },
    desc: {
      en: 'Backup power contractor in Saudi Arabia: standby diesel generators, ATS and synchronisation panels, UPS, battery systems and maintenance.',
      ar: 'مقاول أنظمة الطاقة الاحتياطية في السعودية: مولدات ديزل احتياطية، ولوحات التحويل التلقائي والمزامنة، ووحدات UPS، وأنظمة البطاريات والصيانة.',
    },
    h1: { en: 'Backup power <em>that never misses a beat</em>', ar: 'طاقة احتياطية <em>لا تتوقف</em>' },
    lead: {
      en: 'Generators, UPS and battery systems that keep critical operations running through every outage.',
      ar: 'مولدات ووحدات UPS وأنظمة بطاريات تحافظ على استمرار العمليات الحرجة عند كل انقطاع.',
    },
    chips: [{ en: 'Generators', ar: 'المولدات' }, { en: 'ATS & synch panels', ar: 'لوحات التحويل والمزامنة' }, { en: 'UPS', ar: 'UPS' }, { en: 'Batteries', ar: 'البطاريات' }],
    overview: [
      {
        en: 'For hospitals, data rooms, factories, hotels and towers, a power cut is never just an inconvenience. Barakat Arabia designs and installs power storage and backup systems that take over automatically and safely.',
        ar: 'بالنسبة للمستشفيات وغرف البيانات والمصانع والفنادق والأبراج، لا يُعد انقطاع الكهرباء مجرد إزعاج. لذلك تصمم البركات العربية أنظمة تخزين الطاقة والطاقة الاحتياطية وتركّبها لتتولى التغذية تلقائياً وبأمان.',
      },
      {
        en: 'We size standby diesel generators and UPS systems from critical-load studies, then install generators with their fuel and exhaust systems, automatic transfer switches and synchronisation panels for multiple sets, and UPS and battery systems for sensitive equipment. Every system is load-tested and commissioned with the building’s distribution and BMS, and our maintenance teams keep generators and batteries ready with scheduled runs and inspections. Our industrial and pharmaceutical references include the EPC VCM plant in Alexandria and Badr Pharma in Cairo.',
        ar: 'نحدد قدرات المولدات الاحتياطية ووحدات UPS بناءً على دراسات الأحمال الحرجة، ثم نركّب المولدات مع أنظمة الوقود والعادم، ولوحات التحويل التلقائي، ولوحات المزامنة لمجموعات المولدات المتعددة، ووحدات UPS وأنظمة البطاريات للمعدات الحساسة. تُختبر كل الأنظمة تحت الحمل وتُشغّل بالتكامل مع لوحات توزيع المبنى ونظام إدارة المباني، وتحافظ فرق الصيانة لدينا على جاهزية المولدات والبطاريات عبر تشغيل وفحوص مجدولة. ومن مراجعنا الصناعية والدوائية مصنع VCM التابع لشركة البتروكيماويات المصرية بالإسكندرية ومصنع بدر فارما بالقاهرة.',
      },
    ],
    scopeTitle: { en: 'What we deliver', ar: 'ما نقدمه' },
    scope: [
      { en: 'Standby diesel generators', ar: 'مولدات الديزل الاحتياطية' },
      { en: 'Automatic transfer switches (ATS)', ar: 'مفاتيح التحويل التلقائي (ATS)' },
      { en: 'Synchronisation panels', ar: 'لوحات المزامنة' },
      { en: 'UPS systems', ar: 'أنظمة UPS' },
      { en: 'Battery & energy storage systems', ar: 'أنظمة البطاريات وتخزين الطاقة' },
      { en: 'Fuel & exhaust systems', ar: 'أنظمة الوقود والعادم' },
      { en: 'Load-bank testing & commissioning', ar: 'اختبار الأحمال والتشغيل' },
      { en: 'Scheduled maintenance', ar: 'الصيانة المجدولة' },
    ],
    facts: [
      [{ en: 'Systems', ar: 'الأنظمة' }, { en: 'Generators · ATS · UPS', ar: 'مولدات · ATS · UPS' }],
      [{ en: 'Critical loads', ar: 'الأحمال الحرجة' }, { en: 'Healthcare · Data · Industry', ar: 'صحي · بيانات · صناعي' }],
      [{ en: 'Standards', ar: 'المعايير' }, { en: 'IEC · NFPA', ar: 'IEC · NFPA' }],
      [{ en: 'Coverage', ar: 'نطاق العمل' }, { en: 'Riyadh · Jeddah · KSA', ar: 'الرياض · جدة · المملكة' }],
    ],
    process: [
      { t: { en: 'Critical-load study', ar: 'دراسة الأحمال الحرجة' }, d: { en: 'Identify essential loads and autonomy needs, then size generators and UPS.', ar: 'تحديد الأحمال الأساسية ومدة التشغيل المطلوبة، ثم تحديد قدرات المولدات ووحدات UPS.' } },
      { t: { en: 'Equipment selection', ar: 'اختيار المعدات' }, d: { en: 'Generators, switchgear, UPS and batteries submitted and approved.', ar: 'اعتماد المولدات واللوحات ووحدات UPS والبطاريات.' } },
      { t: { en: 'Installation', ar: 'التركيب' }, d: { en: 'Sets, fuel, exhaust, transfer and synchronisation panels installed.', ar: 'تركيب المولدات وأنظمة الوقود والعادم ولوحات التحويل والمزامنة.' } },
      { t: { en: 'Load testing', ar: 'اختبار الأحمال' }, d: { en: 'Load-bank tests, transfer tests and integration with the BMS.', ar: 'اختبارات الأحمال، واختبارات التحويل، والربط مع نظام إدارة المباني.' } },
    ],
    faq: [
      { q: { en: 'What size generator does my building need?', ar: 'ما قدرة المولد التي يحتاجها مبناي؟' }, a: { en: 'It depends on which loads must stay on during an outage and for how long. We carry out a critical-load study and size the generator, ATS and fuel storage accordingly.', ar: 'يعتمد ذلك على الأحمال التي يجب أن تستمر أثناء الانقطاع ومدة تشغيلها. نجري دراسة للأحمال الحرجة ونحدد قدرة المولد ولوحة التحويل وسعة تخزين الوقود بناءً عليها.' } },
      { q: { en: 'What is the difference between a UPS and a generator?', ar: 'ما الفرق بين وحدة UPS والمولد؟' }, a: { en: 'A UPS provides instant, uninterrupted power from batteries for sensitive equipment. A generator starts within seconds and supplies larger loads for longer periods. Most critical facilities use both.', ar: 'توفر وحدة UPS طاقة فورية دون انقطاع من البطاريات للمعدات الحساسة، بينما يبدأ المولد العمل خلال ثوانٍ ويغذي أحمالاً أكبر لفترات أطول. وتستخدم معظم المنشآت الحرجة كليهما.' } },
      { q: { en: 'Can multiple generators work together?', ar: 'هل يمكن تشغيل عدة مولدات معاً؟' }, a: { en: 'Yes. Synchronisation panels let several generator sets share the load, add redundancy and run efficiently at partial loads.', ar: 'نعم، تتيح لوحات المزامنة لعدة مولدات تقاسم الحمل، وتوفير احتياطية إضافية، والعمل بكفاءة عند الأحمال الجزئية.' } },
      { q: { en: 'Do you maintain generators and UPS systems?', ar: 'هل تقدمون صيانة للمولدات ووحدات UPS؟' }, a: { en: 'Yes. Scheduled maintenance includes test runs, fluid and filter changes, battery checks and transfer tests, so backup power is ready when needed.', ar: 'نعم، تشمل الصيانة المجدولة التشغيل الاختباري، وتغيير الزيوت والفلاتر، وفحص البطاريات، واختبارات التحويل، لتكون الطاقة الاحتياطية جاهزة عند الحاجة.' } },
    ],
    related: ['epc-vcm-alexandria', 'badr-pharma-cairo', 'misk-city-mobility-hub', 'town-way-mall-badr-city'],
  },

  {
    slug: 'mep-facility-management',
    icon: 'wrench',
    img: { base: 'img/gallery-08', widths: [600, 1000, 1800] },
    imgAlt: { en: 'Air handling units and insulated ductwork', ar: 'وحدات مناولة الهواء ومجاري هواء معزولة' },
    name: { en: 'MEP Facility Management', ar: 'إدارة مرافق الأنظمة الكهروميكانيكية' },
    short: { en: 'MEP facility management', ar: 'إدارة المرافق والصيانة' },
    card: { en: 'Preventive maintenance, call-outs and plant operation.', ar: 'الصيانة الوقائية والاستجابة للأعطال وتشغيل المحطات.' },
    seoTitle: { en: 'MEP Maintenance & Facility Management KSA | Barakat Arabia', ar: 'صيانة الأنظمة الكهروميكانيكية وإدارة المرافق | البركات العربية' },
    desc: {
      en: 'MEP maintenance and facility management in Saudi Arabia: preventive maintenance, call-outs and operation of HVAC, electrical, plumbing and fire systems.',
      ar: 'صيانة الأنظمة الكهروميكانيكية وإدارة المرافق في السعودية: صيانة وقائية مخططة، واستجابة للأعطال، وتشغيل أنظمة التكييف والكهرباء والسباكة والحريق.',
    },
    h1: { en: 'MEP facility management <em>that protects your assets</em>', ar: 'إدارة مرافق كهروميكانيكية <em>تحمي أصولك</em>' },
    lead: {
      en: 'Operation and maintenance that keeps mechanical, electrical and plumbing systems efficient, safe and running.',
      ar: 'تشغيل وصيانة تحافظ على كفاءة الأنظمة الميكانيكية والكهربائية والصحية وسلامتها واستمرار عملها.',
    },
    chips: [{ en: 'Preventive maintenance', ar: 'الصيانة الوقائية' }, { en: 'Call-outs', ar: 'الاستجابة للأعطال' }, { en: 'Plant operation', ar: 'تشغيل المحطات' }, { en: 'Energy savings', ar: 'ترشيد الطاقة' }],
    overview: [
      {
        en: 'The systems we install are built to last decades — if they are looked after. Barakat Arabia’s MEP facility management service keeps buildings comfortable, compliant and efficient long after handover.',
        ar: 'صُممت الأنظمة التي نركّبها لتعمل لعقود، شريطة أن تحظى بالعناية المناسبة. وتحافظ خدمة إدارة مرافق الأنظمة الكهروميكانيكية لدى البركات العربية على راحة المباني وتوافقها وكفاءتها لفترة طويلة بعد التسليم.',
      },
      {
        en: 'We take over the operation and maintenance of HVAC plant, electrical distribution, generators and UPS, plumbing and pumps, fire protection and BMS. Planned preventive maintenance follows manufacturer recommendations, reactive call-outs are handled by trained technicians, and regular reports track asset condition, faults and energy use. Because our engineers design and install these same systems, they diagnose problems quickly and recommend upgrades that lower running costs. We maintain buildings we delivered and those installed by others.',
        ar: 'نتولى تشغيل وصيانة محطات التكييف، ولوحات التوزيع الكهربائية، والمولدات ووحدات UPS، والأعمال الصحية والمضخات، وأنظمة الحماية من الحريق، وأنظمة إدارة المباني. تتبع الصيانة الوقائية المخططة توصيات المصنعين، ويتعامل فنيون مدربون مع بلاغات الأعطال، وتتابع التقارير الدورية حالة الأصول والأعطال واستهلاك الطاقة. ولأن مهندسينا يصممون هذه الأنظمة ويركّبونها، فهم يشخصون المشكلات بسرعة ويوصون بالتحسينات التي تخفض تكاليف التشغيل. ونصون المباني التي نفذناها وكذلك المباني التي نفذها مقاولون آخرون.',
      },
    ],
    scopeTitle: { en: 'What we deliver', ar: 'ما نقدمه' },
    scope: [
      { en: 'Planned preventive maintenance', ar: 'الصيانة الوقائية المخططة' },
      { en: 'Reactive & emergency call-outs', ar: 'الاستجابة للأعطال والطوارئ' },
      { en: 'HVAC & chiller maintenance', ar: 'صيانة التكييف والمبردات' },
      { en: 'Electrical, generator & UPS maintenance', ar: 'صيانة الكهرباء والمولدات وUPS' },
      { en: 'Plumbing & pump maintenance', ar: 'صيانة السباكة والمضخات' },
      { en: 'Fire system inspection & testing', ar: 'فحص واختبار أنظمة الحريق' },
      { en: 'BMS monitoring & optimisation', ar: 'مراقبة وتحسين نظام إدارة المباني' },
      { en: 'Asset condition & energy reports', ar: 'تقارير حالة الأصول والطاقة' },
    ],
    facts: [
      [{ en: 'Systems', ar: 'الأنظمة' }, { en: 'HVAC · Electrical · Plumbing · Fire', ar: 'تكييف · كهرباء · سباكة · حريق' }],
      [{ en: 'Service', ar: 'الخدمة' }, { en: 'PPM · Call-outs · Operation', ar: 'صيانة وقائية · أعطال · تشغيل' }],
      [{ en: 'Sectors', ar: 'القطاعات' }, { en: 'Commercial · Hospitality · Healthcare', ar: 'تجاري · فندقي · صحي' }],
      [{ en: 'Coverage', ar: 'نطاق العمل' }, { en: 'Riyadh · Jeddah · KSA', ar: 'الرياض · جدة · المملكة' }],
    ],
    process: [
      { t: { en: 'Asset survey', ar: 'حصر الأصول' }, d: { en: 'Register of equipment, condition assessment and risk review.', ar: 'سجل المعدات وتقييم حالتها ومراجعة المخاطر.' } },
      { t: { en: 'Maintenance plan', ar: 'خطة الصيانة' }, d: { en: 'PPM schedules, response times and reporting agreed with you.', ar: 'جداول الصيانة الوقائية وأزمنة الاستجابة والتقارير بالاتفاق معك.' } },
      { t: { en: 'Delivery', ar: 'التنفيذ' }, d: { en: 'Scheduled maintenance, call-outs and plant operation by trained teams.', ar: 'صيانة مجدولة واستجابة للأعطال وتشغيل المحطات بواسطة فرق مدربة.' } },
      { t: { en: 'Review & improve', ar: 'المراجعة والتحسين' }, d: { en: 'Regular reports and recommendations to cut faults and energy costs.', ar: 'تقارير دورية وتوصيات لتقليل الأعطال وتكاليف الطاقة.' } },
    ],
    faq: [
      { q: { en: 'What does MEP facility management include?', ar: 'ماذا تشمل إدارة مرافق الأنظمة الكهروميكانيكية؟' }, a: { en: 'Operation and maintenance of a building’s mechanical, electrical and plumbing systems — planned preventive maintenance, breakdown response, plant operation, inspections, and reporting on asset condition and energy use.', ar: 'تشمل تشغيل وصيانة الأنظمة الميكانيكية والكهربائية والصحية في المبنى، من صيانة وقائية مخططة واستجابة للأعطال وتشغيل للمحطات وفحوص دورية، إلى تقارير حالة الأصول واستهلاك الطاقة.' } },
      { q: { en: 'Do you maintain systems installed by other contractors?', ar: 'هل تصونون أنظمة نفذها مقاولون آخرون؟' }, a: { en: 'Yes. We start with an asset survey and condition assessment, then build a maintenance plan for the existing systems.', ar: 'نعم، نبدأ بحصر الأصول وتقييم حالتها، ثم نضع خطة صيانة للأنظمة القائمة.' } },
      { q: { en: 'Why is preventive maintenance important?', ar: 'لماذا تُعد الصيانة الوقائية مهمة؟' }, a: { en: 'Regular maintenance prevents costly breakdowns, extends equipment life, keeps life-safety systems ready and reduces energy consumption.', ar: 'تمنع الصيانة الدورية الأعطال المكلفة، وتطيل عمر المعدات، وتحافظ على جاهزية أنظمة السلامة، وتخفض استهلاك الطاقة.' } },
      { q: { en: 'Can maintenance be combined with upgrades?', ar: 'هل يمكن الجمع بين الصيانة وأعمال التطوير؟' }, a: { en: 'Yes. As an MEP contractor we can carry out the replacements and energy-saving upgrades our maintenance reports recommend.', ar: 'نعم، بصفتنا مقاولاً للأعمال الكهروميكانيكية يمكننا تنفيذ أعمال الاستبدال والتطوير الموفرة للطاقة التي توصي بها تقارير الصيانة.' } },
    ],
    related: ['hilton-garden-inn-new-cairo', 'jabco-admin-building-cairo', 'misk-city-mobility-hub', 'wilma-towers-nairobi'],
  },
];

module.exports = { HUB, SERVICES };
